// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBg35Gpf0eeabaABiaLlZg_v-WhXdQGK1A", //leave as it is
      authDomain: "amazn01.firebaseapp.com",
      projectId: "amazn01",
      storageBucket: "amazn01.firebasestorage.app",
      messagingSenderId: "781560053309",
      appId: "1:781560053309:android:1594ac506174c5365cf454",
      measurementId: "G-20QEM6J34W"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg35Gpf0eeabaABiaLlZg_v-WhXdQGK1A', // leave as it is
    appId: '1:781560053309:android:1594ac506174c5365cf454',
    messagingSenderId: '781560053309',
    projectId: 'amazn01',
    storageBucket: 'amazn01.firebasestorage.app', // remove gs://
  );
}
